version: "3.9"

volumes:
  postgres_volume:

services:
#  chat-server:
#    image: chat-server
#    container_name: chat-server
#    ports:
#      - 8085:8085
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
  pg-chat-server:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat-server-pg
    ports:
      - "54321:5432"
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data