version: "3.9"

volumes:
  postgres_volume:

services:
  chat-server:
    image: chat-server
    container_name: chat-server
    ports:
      - 8085:8085
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
     - chat-server-network
  pg-chat-server:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat-server-pg
    ports:
      - "5432:5432"
    restart: always
    networks:
      - chat-server-network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

networks:
  chat-server-network:
    driver: bridge