// Code generated by http://github.com/gojuno/minimock (v3.3.14). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/VadimGossip/consoleChat-chat-server/internal/model"
	"github.com/gojuno/minimock/v3"
)

// AuditServiceMock implements service.AuditService
type AuditServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, audit *model.Audit) (err error)
	inspectFuncCreate   func(ctx context.Context, audit *model.Audit)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mAuditServiceMockCreate
}

// NewAuditServiceMock returns a mock for service.AuditService
func NewAuditServiceMock(t minimock.Tester) *AuditServiceMock {
	m := &AuditServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mAuditServiceMockCreate{mock: m}
	m.CreateMock.callArgs = []*AuditServiceMockCreateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuditServiceMockCreate struct {
	optional           bool
	mock               *AuditServiceMock
	defaultExpectation *AuditServiceMockCreateExpectation
	expectations       []*AuditServiceMockCreateExpectation

	callArgs []*AuditServiceMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// AuditServiceMockCreateExpectation specifies expectation struct of the AuditService.Create
type AuditServiceMockCreateExpectation struct {
	mock      *AuditServiceMock
	params    *AuditServiceMockCreateParams
	paramPtrs *AuditServiceMockCreateParamPtrs
	results   *AuditServiceMockCreateResults
	Counter   uint64
}

// AuditServiceMockCreateParams contains parameters of the AuditService.Create
type AuditServiceMockCreateParams struct {
	ctx   context.Context
	audit *model.Audit
}

// AuditServiceMockCreateParamPtrs contains pointers to parameters of the AuditService.Create
type AuditServiceMockCreateParamPtrs struct {
	ctx   *context.Context
	audit **model.Audit
}

// AuditServiceMockCreateResults contains results of the AuditService.Create
type AuditServiceMockCreateResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mAuditServiceMockCreate) Optional() *mAuditServiceMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for AuditService.Create
func (mmCreate *mAuditServiceMockCreate) Expect(ctx context.Context, audit *model.Audit) *mAuditServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AuditServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &AuditServiceMockCreateParams{ctx, audit}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for AuditService.Create
func (mmCreate *mAuditServiceMockCreate) ExpectCtxParam1(ctx context.Context) *mAuditServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AuditServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &AuditServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx

	return mmCreate
}

// ExpectAuditParam2 sets up expected param audit for AuditService.Create
func (mmCreate *mAuditServiceMockCreate) ExpectAuditParam2(audit *model.Audit) *mAuditServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AuditServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &AuditServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.audit = &audit

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the AuditService.Create
func (mmCreate *mAuditServiceMockCreate) Inspect(f func(ctx context.Context, audit *model.Audit)) *mAuditServiceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for AuditServiceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by AuditService.Create
func (mmCreate *mAuditServiceMockCreate) Return(err error) *AuditServiceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AuditServiceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &AuditServiceMockCreateResults{err}
	return mmCreate.mock
}

// Set uses given function f to mock the AuditService.Create method
func (mmCreate *mAuditServiceMockCreate) Set(f func(ctx context.Context, audit *model.Audit) (err error)) *AuditServiceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the AuditService.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the AuditService.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the AuditService.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mAuditServiceMockCreate) When(ctx context.Context, audit *model.Audit) *AuditServiceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuditServiceMock.Create mock is already set by Set")
	}

	expectation := &AuditServiceMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &AuditServiceMockCreateParams{ctx, audit},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up AuditService.Create return parameters for the expectation previously defined by the When method
func (e *AuditServiceMockCreateExpectation) Then(err error) *AuditServiceMock {
	e.results = &AuditServiceMockCreateResults{err}
	return e.mock
}

// Times sets number of times AuditService.Create should be invoked
func (mmCreate *mAuditServiceMockCreate) Times(n uint64) *mAuditServiceMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of AuditServiceMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	return mmCreate
}

func (mmCreate *mAuditServiceMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements service.AuditService
func (mmCreate *AuditServiceMock) Create(ctx context.Context, audit *model.Audit) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, audit)
	}

	mm_params := AuditServiceMockCreateParams{ctx, audit}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := AuditServiceMockCreateParams{ctx, audit}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("AuditServiceMock.Create got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.audit != nil && !minimock.Equal(*mm_want_ptrs.audit, mm_got.audit) {
				mmCreate.t.Errorf("AuditServiceMock.Create got unexpected parameter audit, want: %#v, got: %#v%s\n", *mm_want_ptrs.audit, mm_got.audit, minimock.Diff(*mm_want_ptrs.audit, mm_got.audit))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("AuditServiceMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the AuditServiceMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, audit)
	}
	mmCreate.t.Fatalf("Unexpected call to AuditServiceMock.Create. %v %v", ctx, audit)
	return
}

// CreateAfterCounter returns a count of finished AuditServiceMock.Create invocations
func (mmCreate *AuditServiceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of AuditServiceMock.Create invocations
func (mmCreate *AuditServiceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to AuditServiceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mAuditServiceMockCreate) Calls() []*AuditServiceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*AuditServiceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *AuditServiceMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *AuditServiceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuditServiceMock.Create with params: %#v", *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to AuditServiceMock.Create")
		} else {
			m.t.Errorf("Expected call to AuditServiceMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Error("Expected call to AuditServiceMock.Create")
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to AuditServiceMock.Create but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), afterCreateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuditServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuditServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuditServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone()
}
